# Generated by Django 4.1.3 on 2022-11-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=4, unique=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "nearest_codes",
                    models.ManyToManyField(related_name="+", to="listings.outcode"),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AirBnbListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("air_bnb_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=1024)),
                ("host_id", models.PositiveIntegerField()),
                ("host_name", models.CharField(max_length=1024)),
                ("neighbourhood_group", models.CharField(max_length=255)),
                ("neighbourhood", models.CharField(max_length=255)),
                ("room_type", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("minimum_nights", models.PositiveIntegerField()),
                ("number_of_reviews", models.PositiveIntegerField()),
                ("number_of_reviews_ltm", models.PositiveIntegerField()),
                ("last_review", models.DateField(blank=True, null=True)),
                ("reviews_per_month", models.FloatField(blank=True, null=True)),
                ("calculated_host_listings_count", models.PositiveIntegerField()),
                ("availability_365", models.PositiveIntegerField()),
                ("license", models.CharField(max_length=255)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "outcode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="listings.outcode",
                    ),
                ),
            ],
        ),
    ]
